name: build-mgscopebar

on: [pull_request]

jobs:
  buildGitx:
    name: Build MGScopeBar
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - name: Build project
        run: set -o pipefail && xcodebuild -workspace MGScopeBar.xcodeproj/project.xcworkspace -scheme MGScopeBar archive | xcpretty

